version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-location
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: location_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
